<strong> World population Dataset </strong>
<p> This notebook will (hopefully) contain all that is necessary to work with the data set. </p>
<p> The country data was obtained as a CSV file from population.un.org </p>

In [1]:
#First read the data set
import requests
import pandas as pd
#path_dir = r"UNPopulationData_Raw.csv"

df = pd.read_csv("UNPopulationData_Raw.csv")
print(df)

       IndicatorId       IndicatorName  \
0               54  Population density
1               54  Population density
2               54  Population density
3               54  Population density
4               54  Population density
...            ...                 ...
18745           54  Population density
18746           54  Population density
18747           54  Population density
18748           54  Population density
18749           54  Population density

                               IndicatorShortName                      Source  \
0      Population density (persons per square km)  World Population Prospects
1      Population density (persons per square km)  World Population Prospects
2      Population density (persons per square km)  World Population Prospects
3      Population density (persons per square km)  World Population Prospects
4      Population density (persons per square km)  World Population Prospects
...                                           ...                         ...
18745  Population density (persons per square km)  World Population Prospects
18746  Population density (persons per square km)  World Population Prospects
18747  Population density (persons per square km)  World Population Prospects
18748  Population density (persons per square km)  World Population Prospects
18749  Population density (persons per square km)  World Population Prospects

       SourceYear                              Author  LocationId  \
0            2024  United Nations Population Division           4
1            2024  United Nations Population Division           4
2            2024  United Nations Population Division           4
3            2024  United Nations Population Division           4
4            2024  United Nations Population Division           4
...           ...                                 ...         ...
18745        2024  United Nations Population Division        5505
18746        2024  United Nations Population Division        5505
18747        2024  United Nations Population Division        5505
18748        2024  United Nations Population Division        5505
18749        2024  United Nations Population Division        5505

          Location Iso2 Iso3  ...  AgeStart  AgeEnd    Age CategoryId  \
0      Afghanistan   AF  AFG  ...         0      -1  Total          0
1      Afghanistan   AF  AFG  ...         0      -1  Total          0
2      Afghanistan   AF  AFG  ...         0      -1  Total          0
3      Afghanistan   AF  AFG  ...         0      -1  Total          0
4      Afghanistan   AF  AFG  ...         0      -1  Total          0
...            ...  ...  ...  ...       ...     ...    ...        ...
18745     Americas   AM  AMR  ...         0      -1  Total          0
18746     Americas   AM  AMR  ...         0      -1  Total          0
18747     Americas   AM  AMR  ...         0      -1  Total          0
18748     Americas   AM  AMR  ...         0      -1  Total          0
18749     Americas   AM  AMR  ...         0      -1  Total          0

             Category EstimateTypeId           EstimateType  EstimateMethodId  \
0      Not applicable              1  Model-based Estimates                 2
1      Not applicable              1  Model-based Estimates                 2
2      Not applicable              1  Model-based Estimates                 2
3      Not applicable              1  Model-based Estimates                 2
4      Not applicable              1  Model-based Estimates                 2
...               ...            ...                    ...               ...
18745  Not applicable              1  Model-based Estimates                 2
18746  Not applicable              1  Model-based Estimates                 2
18747  Not applicable              1  Model-based Estimates                 2
18748  Not applicable              1  Model-based Estimates                 2
18749  Not applicable              1  Model-based Estimates                 3

       EstimateMethod      Value
0       Interpolation  11.976319
1       Interpolation  12.135203
2       Interpolation  12.302222
3       Interpolation  12.469964
4       Interpolation  12.641306
...               ...        ...
18745   Interpolation  26.323940
18746   Interpolation  26.445826
18747   Interpolation  26.590781
18748   Interpolation  26.769253
18749      Projection  26.948271

[18750 rows x 27 columns]

In [2]:
# Not so pretty yet, get rid of some columns since we only want the countries and the respective population density according to the years
print(df.columns)

# Remove unnecessary columns
df_slim = pd.DataFrame([df.pop(x) for x in ['Location','Time', 'Value']]).T
print(df_slim)

Index(['IndicatorId', 'IndicatorName', 'IndicatorShortName', 'Source',
       'SourceYear', 'Author', 'LocationId', 'Location', 'Iso2', 'Iso3',
       'TimeId', 'Time', 'VariantId', 'Variant', 'SexId', 'Sex', 'AgeId',
       'AgeStart', 'AgeEnd', 'Age', 'CategoryId', 'Category', 'EstimateTypeId',
       'EstimateType', 'EstimateMethodId', 'EstimateMethod', 'Value'],
      dtype='object')
          Location  Time      Value
0      Afghanistan  1950  11.976319
1      Afghanistan  1951  12.135203
2      Afghanistan  1952  12.302222
3      Afghanistan  1953  12.469964
4      Afghanistan  1954  12.641306
...            ...   ...        ...
18745     Americas  2020   26.32394
18746     Americas  2021  26.445826
18747     Americas  2022  26.590781
18748     Americas  2023  26.769253
18749     Americas  2024  26.948271

[18750 rows x 3 columns]

In [3]:
# Lastly, reorder so that the years are our columns
df_years = df_slim.pivot_table (index = 'Location', columns = 'Time', values = 'Value')

In [4]:
df_years.head()

Time,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Location,,,,,,,,,,,,,,,,,,,,,
Afghanistan,11.976319,12.135203,12.302222,12.469964,12.641306,12.824628,13.02072,13.227149,13.435169,13.659825,...,52.105301,53.44344,54.965585,56.589043,58.303333,60.171292,61.605819,62.496676,63.845705,65.682666
Africa,7.707906,7.869679,8.038288,8.212412,8.392465,8.579668,8.773691,8.971898,9.171996,9.382813,...,41.287099,42.340632,43.413139,44.513191,45.616223,46.726699,47.841107,48.96224,50.108964,51.272049
Albania,45.545332,46.586083,47.753851,49.039182,50.408314,51.786609,53.172494,54.673918,56.353694,58.21633,...,105.797211,105.769271,105.782995,105.636579,105.300004,104.823473,104.008888,103.204905,102.622637,101.896653
Algeria,3.786487,3.892056,3.997585,4.103154,4.204649,4.302495,4.401061,4.499862,4.599007,4.698087,...,16.802644,17.151629,17.503715,17.846211,18.177696,18.491561,18.793445,19.094187,19.38256,19.655507
American Samoa,95.2125,97.1275,97.765,98.33,98.7975,99.2925,99.6825,99.79,99.6525,99.5425,...,264.39,261.2225,257.93,254.5425,251.045,248.8075,246.125,241.7075,237.605,233.825

In [5]:
df_years.to_csv('population_data.csv')